plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

base {
    archivesName = "${mod_id}-${minecraft_version}-Fabric"
}

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Nucleoid"
        url = "https://maven.nucleoid.xyz/"
    }
}

dependencies {
    implementation "com.electronwill.night-config:core:3.8.3"
    implementation "com.electronwill.night-config:toml:3.8.3"
    implementation "com.electronwill.night-config:json:3.8.3"
    implementation "com.electronwill.night-config:hocon:3.8.3"
    implementation "com.electronwill.night-config:yaml:3.8.3"

    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation "curse.maven:forge-config-api-port-547434:7807872"
    compileOnly "curse.maven:irisshaders-455508:7805235"
    compileOnly "curse.maven:sodium-394468:7805119"
    implementation("com.terraformersmc:modmenu:${modmenu_version}")
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
